### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by mifrey00** [Razzeee/context.trakt.contextmenu#8]
Platform: OSMC, Kodi 19.4 

Same error whatever the option I select (Add to watchlist, rate, etc.).

```
2022-12-28 18:23:03.227 T:12349    INFO <general>: CPythonInvoker(111, /home/osmc/.kodi/addons/context.trakt.contextmenu/addon.py): script successfully run
2022-12-28 18:23:03.240 T:12349    INFO <general>: Python interpreter stopped
2022-12-28 18:23:03.276 T:12350    INFO <general>: initializing python engine.
2022-12-28 18:23:05.054 T:12350    INFO <general>: start trakt with arguments: {'action': 'contextmenu'}
2022-12-28 18:23:05.057 T:12350    INFO <general>: list item type: movie
2022-12-28 18:23:05.067 T:9716     INFO <general>: Loading skin file: /home/osmc/.kodi/addons/script.trakt/resources/skins/Default/720p/script-trakt-ContextMenu.xml, load type: LOAD_ON_GUI_INIT
2022-12-28 18:23:05.074 T:9716    ERROR <general>: Control 111 in window 13002 has been asked to focus, but it can't
2022-12-28 18:23:10.192 T:12350    INFO <general>: list item type: movie
2022-12-28 18:23:10.201 T:12350   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: invalid literal for int() with base 10: ''
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.trakt/defaultscript.py", line 14, in <module>
                                                       Main()
                                                     File "/home/osmc/.kodi/addons/script.trakt/defaultscript.py", line 11, in Main
                                                       script.run()
                                                     File "/home/osmc/.kodi/addons/script.trakt/resources/lib/script.py", line 298, in run
                                                       dbid = int(xbmc.getInfoLabel('ListItem.DBID'))
                                                   ValueError: invalid literal for int() with base 10: ''
                                                   -->End of Python script error report<--

```

**Comment by razzeee** [comment]
Is this with the estuary skin?

**Comment by mifrey00** [comment]
No with the Arctic Zephyr Reloaded skin.

**Comment by razzeee** [comment]
Please try with the default skin

**Comment by mifrey00** [comment]
Same error:
 ```
2022-12-28 20:08:19.176 T:9716     INFO <general>:   load skin from: /usr/share/kodi/addons/skin.estuary/ (version: 3.0.5)
...
2022-12-28 20:08:19.891 T:9716     INFO <general>:   skin loaded...
....
2022-12-28 20:10:17.328 T:12770    INFO <general>: initializing python engine.
2022-12-28 20:10:17.637 T:12770    INFO <general>: CPythonInvoker(124, /home/osmc/.kodi/addons/context.trakt.contextmenu/addon.py): script successfully run
2022-12-28 20:10:17.643 T:12771    INFO <general>: initializing python engine.
2022-12-28 20:10:17.650 T:12770    INFO <general>: Python interpreter stopped
2022-12-28 20:10:19.348 T:12771    INFO <general>: start trakt with arguments: {'action': 'contextmenu'}
2022-12-28 20:10:19.349 T:12771    INFO <general>: list item type: movie
2022-12-28 20:10:19.358 T:9716     INFO <general>: Loading skin file: /home/osmc/.kodi/addons/script.trakt/resources/skins/Default/720p/script-trakt-ContextMenu.xml, load type: LOAD_ON_GUI_INIT
2022-12-28 20:10:19.362 T:9716    ERROR <general>: Control 111 in window 13002 has been asked to focus, but it can't
2022-12-28 20:10:23.909 T:12771    INFO <general>: list item type: movie
2022-12-28 20:10:23.916 T:12771   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: invalid literal for int() with base 10: ''
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.trakt/defaultscript.py", line 14, in <module>
                                                       Main()
                                                     File "/home/osmc/.kodi/addons/script.trakt/defaultscript.py", line 11, in Main
                                                       script.run()
                                                     File "/home/osmc/.kodi/addons/script.trakt/resources/lib/script.py", line 298, in run
                                                       dbid = int(xbmc.getInfoLabel('ListItem.DBID'))
                                                   ValueError: invalid literal for int() with base 10: ''
                                                   -->End of Python script error report<--

```

**Comment by razzeee** [comment]
I can't reproduce this, it might be caused by your video data source.

**Comment by pippaine** [comment]
I am experiencing this same issue on Kodi 20. It happens everywhere, regardless of skin or video source.
